# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liquid development team
email: Liquid@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  The Liquid quantum simulator
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://research.microsoft.com/projects/Liquid" # the base hostname & protocol for your site
twitter_username: StationQ
github_username:  StationQ

# Build settings
markdown: kramdown
